### ISSUE TITLE
feat: setup backend

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#10]
create or setup basic backend for the codeEditor platform

**Comment by chihab1991** [comment]
can you add which tech you want to use for your backend.

**Comment by cpwallah** [comment]
hi @vaibhavvatsbhartiya i would like to work on this issue

**Comment by vaibhavvatsbhartiya** [comment]
well guys our stack is MERN stack and if possible then you can work on our frontend issues first. go and check it out i will update there time to time.

Forntend: Reactjs and Tailwind CSS

do not use any other UI library or different stack because in that case your code is not merged.

Thank you
Vaibhav Vats
