### ISSUE TITLE
feat: Create a HomePage.jsx

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#16]
Here your task is to create a Home page as shown in the image.

Place the page in pages folder of our code base.

![image](https://github.com/code-Atish/codeEditor/assets/76244950/5b52d29e-63de-4ef4-91f7-8bc3b904e982)

**Comment by code-Atish** [comment]
I will try to work on it.

**Comment by code-Atish** [comment]
Update : Homepage 
doubt : Do I have to replicate entire home page as it is from hackerrank?
![localhost_5173_ (1)](https://github.com/code-Atish/codeEditor/assets/118765211/970b35e2-c4cc-49c4-a2cb-4bdcfb42f000)
