### ISSUE TITLE
feat: access account page

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#18]
your task is to create a AccessAccountPage.jsx in the page folder of our code base and make sure it should be responsive. 

![image](https://github.com/code-Atish/codeEditor/assets/76244950/3123a77f-c8aa-447c-88db-c11ba43464d4)

**Comment by Jagdeesh9** [comment]
I WANT TO WORK ON THIS, I HAVE TO MAKE NAV YES OR  NO

**Comment by vaibhavvatsbhartiya** [comment]
currently you can create it we will update the code in future. make sure to use word like Navbar2.jsx of AccessAccountNavbar.jsx name it which you like but that name reflect the above too. And as current as we need a new navbar then go to issue and create one. Start working on it first then come back to this one. 
Thank you.

**Comment by Jagdeesh9** [comment]
CAN YOU SHARE THE WEBSITE IMAGE IN SMALL SCREEN

**Comment by vaibhavvatsbhartiya** [comment]
go to hackerrank.com/ account access something like that.
