### ISSUE TITLE
bug: change the name of web application

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#20]
change the name of HackerRank to Upto Skills in the entire code base.

**Comment by Rajvardhan222** [comment]
please assign this to me

**Comment by Techcode123** [comment]
I want to work on this particular issue

**Comment by devansh-dek** [comment]
Can i work on this ?

**Comment by chihab1991** [comment]
hey i can help with this one.

**Comment by chihab1991** [comment]
i found that the word hackerrank exists also in ancher tags in footer should i remplace the links also?
![image](https://github.com/user-attachments/assets/5e0f2b25-8a11-49d4-9832-b9d68202a379)

**Comment by vaibhavvatsbhartiya** [comment]
yes change all to upto skills according to need
