### ISSUE TITLE
feat: Need changes in Navbar.jsx

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#28]
You need to use react-router-dom such that our navbar start function and also change the name HackerRank-->UptoSkills. 
Also You need to Name the page accordingly in Navbar.

https://github.com/code-Atish/codeEditor/blob/main/frontend/src/components/Navbar.jsx

**Comment by chihab1991** [comment]
hi I think i can work on this one.

**Comment by chihab1991** [comment]
are the these links to different pages? also there are no Services , about or contact pages.
please let me know how you want to structure these app so i can configure this router properly

**Comment by vaibhavvatsbhartiya** [comment]
well Services , about or contact are just random names in order to give UI to navbar. mainly we use this nav in order to go to one page to another present in pages section.

**Comment by chihab1991** [comment]
to create a functioning navbar with react-router-dom
we need to modify `main.jsx` and `app.jsx` and it will be preferable to create a `Layout` file where we fix the navbar w and the footer and only change the content of the page with react-router

**Comment by vaibhavvatsbhartiya** [comment]
yes absolutely
