### ISSUE TITLE
feat: create a card component showing overview of problem

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#6]
create a design like shown in the photo below. It should be responsive and working properly.
its a component so create file in component folder and give it a meaning full name.

Playing With Characters is heading exactly. so, use h2 or h3 accordingly which suits the design.

![image](https://github.com/code-Atish/codeEditor/assets/76244950/6fe340bc-5d4c-4ec3-9e40-7a4a07a03099)

**Comment by Jagdeesh9** [comment]
i want to work on this
