### ISSUE TITLE
feat: Creation of ProblemPage.jsx

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#7]
Here we work on after the completion of issue https://github.com/code-Atish/codeEditor/issues/5 and https://github.com/code-Atish/codeEditor/issues/6 .

Now create a page named ProblemPage.jsx and UI design same as area mark within red line in image below:

![image](https://github.com/code-Atish/codeEditor/assets/76244950/62cbf907-2790-4203-98ce-53c6e68dddd8)

**Comment by kirtikganesan** [comment]
I will try to work on this

**Comment by Shrutam05** [comment]
I will try to tackle this task
