### ISSUE TITLE
feat: create a readme file 

### ISSUE THREAD

**Issue by vaibhavvatsbhartiya** [code-Atish/codeEditor#9]
create a readme file explaining about frontend folder and the status of that folder like how much we complete the work and on which functions we are working in future

**Comment by jackabald** [comment]
Hey! I can update your readme file to be more comprehensive. Additionally, I can merge all your readme files into the root readme file, keeping all their information and just combining it into one file.

Please assign me the issue if you would like this done!

Thanks!
